/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : SPI2.c
**     Project     : ProcessorExpert
**     Processor   : MK60DN512VLQ10
**     Component   : Init_SPI
**     Version     : Component 01.003, Driver 01.03, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-12-10, 07:59, # CodeGen: 5
**     Abstract    :
**          This file implements the SPI (SPI2) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : SPI2
**          Device                                         : SPI2
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Configuration 0                              : Master
**              Clock setting                              : 
**                Baud rate prescaler                      : divide by 2
**                Double baud rate                         : Disabled
**                Baud rate scaler                         : divide by 2
**                DSPI frequency                           : 12 MHz
**                PCS to SCK delay prescaler               : divide by 1
**                PCS to SCK delay scaler                  : divide by 2
**                PCS to SCK delay                         : 0.042 us
**                After SCK delay prescaler                : divide by 1
**                After SCK delay scaler                   : divide by 2
**                After SCK delay                          : 0.042 us
**                Delay after transfer prescaler           : divide by 1
**                Delay after transfer scaler              : divide by 2
**                Delay after transfer                     : 0.042 us
**              Transfer size                              : 16
**              Clock polarity                             : Low
**              Clock phase                                : Capture on leading edge
**              LSB first                                  : Disabled
**            Configuration 1                              : Master
**              Clock setting                              : 
**                Baud rate prescaler                      : divide by 2
**                Double baud rate                         : Disabled
**                Baud rate scaler                         : divide by 2
**                DSPI frequency                           : 12 MHz
**                PCS to SCK delay prescaler               : divide by 1
**                PCS to SCK delay scaler                  : divide by 2
**                PCS to SCK delay                         : 0.042 us
**                After SCK delay prescaler                : divide by 1
**                After SCK delay scaler                   : divide by 2
**                After SCK delay                          : 0.042 us
**                Delay after transfer prescaler           : divide by 1
**                Delay after transfer scaler              : divide by 2
**                Delay after transfer                     : 0.042 us
**              Transfer size                              : 16
**              Clock polarity                             : Low
**              Clock phase                                : Capture on leading edge
**              LSB first                                  : Disabled
**            Master mode                                  : Disabled
**            Continuous SCK                               : Disabled
**            Freeze                                       : Do not halt transfers
**            Doze                                         : Disabled
**            Modified timing format                       : Disabled
**            Peripheral chip select strobe                : Disabled
**            Rx FIFO overflow overwrite                   : Disabled
**            PCS0 inactive level                          : Low
**            PCS1 inactive level                          : Low
**            TxFIFO                                       : Enabled
**            RxFIFO                                       : Enabled
**            Sample point                                 : 0 system clocks
**          Pins                                           : 
**            Data input pin                               : Enabled
**              Pin                                        : PTD14/SPI2_SIN/SDHC0_D6/FB_AD5/FB_A22
**              Pin signal                                 : 
**            Data output pin                              : Enabled
**              Pin                                        : PTD13/SPI2_SOUT/SDHC0_D5/FB_AD6/FB_A21
**              Pin signal                                 : 
**            Clock output pin                             : Enabled
**              Pin                                        : PTD12/SPI2_SCK/SDHC0_D4/FB_AD7/FB_A20
**              Pin signal                                 : 
**            Peripheral select 0 pin                      : Enabled
**              Pin                                        : PTD11/SPI2_PCS0/UART5_CTS_b/SDHC0_CLKIN/FB_AD8/FB_A19
**              Pin signal                                 : 
**            Peripheral select 1 pin                      : Enabled
**              Pin                                        : PTD15/SPI2_PCS1/SDHC0_D7/FB_RW_b/FB_A23
**              Pin signal                                 : 
**          Interrupts/DMA                                 : 
**            Interrupt                                    : INT_SPI2
**            Interrupt request                            : Disabled
**            Interrupt priority                           : 0 (Highest)
**            ISR Name                                     : 
**            DSPI finished interrupt                      : Disabled
**            Transmission complete interrupt              : Disabled
**            Tx FIFO fill request                         : Disabled
**            Tx FIFO fill request type                    : interrupt
**            Tx FIFO underflow interrupt                  : Disabled
**            Rx FIFO drain request                        : Disabled
**            Rx FIFO drain request type                   : interrupt
**            Rx FIFO overflow interrupt                   : Disabled
**          Initialization                                 : 
**            Transfer counter                             : 0
**            Module disable                               : yes
**            Halt                                         : yes
**            Call Init method                             : no
**     Contents    :
**         Init - void SPI2_Init(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file SPI2.c
** @version 01.03
** @brief
**          This file implements the SPI (SPI2) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup SPI2_module SPI2 module documentation
**  @{
*/         

/* MODULE SPI2. */

#include "SPI2.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  SPI2_Init (component Init_SPI)
**     Description :
**         This method initializes registers of the SPI module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void SPI2_Init(void)
{
  /* SIM_SCGC3: SPI2=1 */
  SIM_SCGC3 |= SIM_SCGC3_SPI2_MASK;                                   
  /* SPI2_MCR: MSTR=0,CONT_SCKE=0,DCONF=0,FRZ=0,MTFE=0,PCSSE=0,ROOE=0,??=0,??=0,??=0,PCSIS=0,DOZE=0,MDIS=0,DIS_TXF=0,DIS_RXF=0,CLR_TXF=0,CLR_RXF=0,SMPL_PT=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,HALT=1 */
  SPI2_MCR = SPI_MCR_DCONF(0x00) |
             SPI_MCR_PCSIS(0x00) |
             SPI_MCR_SMPL_PT(0x00) |
             SPI_MCR_HALT_MASK;       
  /* SPI2_MCR: MSTR=0,CONT_SCKE=0,DCONF=0,FRZ=0,MTFE=0,PCSSE=0,ROOE=0,??=0,??=0,??=0,PCSIS=0,DOZE=0,MDIS=0,DIS_TXF=0,DIS_RXF=0,CLR_TXF=1,CLR_RXF=1,SMPL_PT=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,HALT=1 */
  SPI2_MCR = SPI_MCR_DCONF(0x00) |
             SPI_MCR_PCSIS(0x00) |
             SPI_MCR_CLR_TXF_MASK |
             SPI_MCR_CLR_RXF_MASK |
             SPI_MCR_SMPL_PT(0x00) |
             SPI_MCR_HALT_MASK;       
  /* SPI2_TCR: SPI_TCNT=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  SPI2_TCR = SPI_TCR_SPI_TCNT(0x00);                                   
  /* SPI2_CTAR0: DBR=0,FMSZ=0x0F,CPOL=0,CPHA=0,LSBFE=0,PCSSCK=0,PASC=0,PDT=0,PBR=0,CSSCK=0,ASC=0,DT=0,BR=0 */
  SPI2_CTAR0 = SPI_CTAR_FMSZ(0x0F) |
               SPI_CTAR_PCSSCK(0x00) |
               SPI_CTAR_PASC(0x00) |
               SPI_CTAR_PDT(0x00) |
               SPI_CTAR_PBR(0x00) |
               SPI_CTAR_CSSCK(0x00) |
               SPI_CTAR_ASC(0x00) |
               SPI_CTAR_DT(0x00) |
               SPI_CTAR_BR(0x00);       
  /* SPI2_CTAR1: DBR=0,FMSZ=0x0F,CPOL=0,CPHA=0,LSBFE=0,PCSSCK=0,PASC=0,PDT=0,PBR=0,CSSCK=0,ASC=0,DT=0,BR=0 */
  SPI2_CTAR1 = SPI_CTAR_FMSZ(0x0F) |
               SPI_CTAR_PCSSCK(0x00) |
               SPI_CTAR_PASC(0x00) |
               SPI_CTAR_PDT(0x00) |
               SPI_CTAR_PBR(0x00) |
               SPI_CTAR_CSSCK(0x00) |
               SPI_CTAR_ASC(0x00) |
               SPI_CTAR_DT(0x00) |
               SPI_CTAR_BR(0x00);       
  /* SPI2_SR: TCF=1,TXRXS=0,??=0,EOQF=1,TFUF=1,??=0,TFFF=1,??=0,??=0,??=0,??=0,??=0,RFOF=1,??=0,RFDF=1,??=0,TXCTR=0,TXNXTPTR=0,RXCTR=0,POPNXTPTR=0 */
  SPI2_SR = SPI_SR_TCF_MASK |
            SPI_SR_EOQF_MASK |
            SPI_SR_TFUF_MASK |
            SPI_SR_TFFF_MASK |
            SPI_SR_RFOF_MASK |
            SPI_SR_RFDF_MASK |
            SPI_SR_TXCTR(0x00) |
            SPI_SR_TXNXTPTR(0x00) |
            SPI_SR_RXCTR(0x00) |
            SPI_SR_POPNXTPTR(0x00);       
  /* SPI2_RSER: TCF_RE=0,??=0,??=0,EOQF_RE=0,TFUF_RE=0,??=0,TFFF_RE=0,TFFF_DIRS=0,??=0,??=0,??=0,??=0,RFOF_RE=0,??=0,RFDF_RE=0,RFDF_DIRS=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  SPI2_RSER = 0x00U;                                   
  /* SPI2_MCR: MDIS=1 */
  SPI2_MCR |= SPI_MCR_MDIS_MASK;                                   
}


/* END SPI2. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.07]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
