/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : usb_cdc_pstn.c
**     Project   : ProcessorExpert
**     Processor : MK60DN512LQ10
**     Component : USB_CDC_CLASS
**     Version   : Driver 01.00, CPU db: 3.00.000
**     Compiler  : CodeWarrior ARM C Compiler
**     Date/Time : 2013-12-09, 14:17, # CodeGen: 4
**     Abstract  :
**     Settings  :
**     (c) Copyright <company/user-name>, 2011
**     http      : www.<company>.com
**     mail      : info@<company>.com
** ###################################################################*/

 #include "usb_cdc_pstn.h"  /* USB CDC PSTN Sub Class Header File */

/* PSTN subclass callback pointer */
static USB_CLASS_CALLBACK g_pstn_callback = NULL;
/* data terminal equipment present or not */
static boolean g_dte_present = FALSE;
static uint_8 g_dte_status = 0; /* Status of DATA TERMINAL EQUIPMENT */
static uint_16 g_break_duration = 0; /* Length of time in milliseconds of the
                                                              break signal */
static uint_8 g_current_interface = 0;
static UART_BITMAP g_uart_bitmap;
static uint_8 g_serial_state_buf[NOTIF_PACKET_SIZE+UART_BITMAP_SIZE] =
{
    NOTIF_REQUEST_TYPE,SERIAL_STATE_NOTIF,
    0x00,0x00,/*wValue*/
    0x00,0x00,/*interface - modifies*/
    UART_BITMAP_SIZE,0x00,/* wlength*/
    0x00,0x00 /*data initialized - modifies*/
};/*uart bitmap*/
/* Internal method prototypes */



/*
** ===================================================================
**     Method      :  usb_cdc_USB_Class_CDC_Pstn_Init (component USB_CDC_CLASS)
**     Description :
**         The funtion initializes the PSTN Module
**     Parameters  :
**         NAME            - DESCRIPTION
**         controller_ID   - [IN] Controller ID
**         callback        - [IN] PSTN Callback
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint_8 USB_Class_CDC_Pstn_Init(uint_8 controller_ID, USB_CLASS_CALLBACK callback)
{
    uint_8 error = USB_OK;
    UNUSED (controller_ID)

    /* save input parameters */
    g_pstn_callback = callback;
    return error;
}

/*
** ===================================================================
**     Method      :  USB_Class_CDC_PSTN_Get_Line_Coding (component USB_CDC_CLASS)
**     Description :
**         This function is called in response to GetLineCoding request
**     Parameters  :
**         NAME            - DESCRIPTION
**         controller_ID   - [IN] Controller ID
**       * setup_packet    - [IN] Pointer to setup
**                           packet
**       * data            - [OUT] Pointer to Data to be send
**       * size            - [OUT] Pointer to Size of Data
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint_8 USB_Class_CDC_PSTN_Get_Line_Coding(uint_8 controller_ID, USB_SETUP_STRUCT *setup_packet, uint_8_ptr *data, USB_PACKET_SIZE *size)
{
    uint_8 status;
    UNUSED (size)
    g_current_interface = (uint_8)setup_packet->index ;
    status = USB_Desc_Get_Line_Coding(controller_ID, g_current_interface,
        data);
    return status;
}

/*
** ===================================================================
**     Method      :  USB_Class_CDC_PSTN_Set_Line_Coding (component USB_CDC_CLASS)
**     Description :
**         This function is called in response to SetLineCoding request
**     Parameters  :
**         NAME            - DESCRIPTION
**         controller_ID   - [IN] Controller ID
**       * setup_packet    - [IN] Pointer to setup
**                           packet
**       * data            - [OUT] Pointer to Data to be send
**       * size            - [OUT] Pointer to Size of Data
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint_8 USB_Class_CDC_PSTN_Set_Line_Coding(uint_8 controller_ID, USB_SETUP_STRUCT *setup_packet, uint_8_ptr *data, USB_PACKET_SIZE *size)
{
    uint_8 status;
    UNUSED(data)
    *size = 0;
    g_current_interface = (uint_8)setup_packet->index ;
    status = USB_Desc_Set_Line_Coding(controller_ID, g_current_interface,
        (uint_8_ptr *)&setup_packet);
    return status;
}

/*
** ===================================================================
**     Method      :  USB_Class_CDC_PSTN_Set_Ctrl_Line_State (component USB_CDC_CLASS)
**     Description :
**         This function is called in response to Set Control Line State
**     Parameters  :
**         NAME            - DESCRIPTION
**         controller_ID   - [IN] Controller ID
**       * setup_packet    - [IN] Pointer to setup
**                           packet
**       * data            - [OUT] Pointer to Data to be send
**       * size            - [OUT] Pointer to Size of Data
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint_8 USB_Class_CDC_PSTN_Set_Ctrl_Line_State(uint_8 controller_ID, USB_SETUP_STRUCT *setup_packet, uint_8_ptr *data, USB_PACKET_SIZE *size)
{

    UNUSED(data)
    *size = 0;

    g_dte_status = (uint_8)setup_packet->value ;
    g_uart_bitmap._byte = 0x00; /* initialize */
    /* activate/deactivate Tx carrier */
    g_uart_bitmap.Bitmap_Uart.bTxCarrier = (g_dte_status &
        CARRIER_ACTIVATION_CHECK) ? 1 : 0 ;
     /* activate carrier and DTE */
    g_uart_bitmap.Bitmap_Uart.bRxCarrier = (g_dte_status &
        CARRIER_ACTIVATION_CHECK) ? 1 : 0 ;

    /* Indicates to DCE if DTE is present or not */
    g_dte_present = (boolean)((g_dte_status & DTE_PRESENCE_CHECK) ?
        TRUE : FALSE);
    /* Send Notification to Host - Parameter on Device side has changed */
    USB_Class_CDC_PSTN_Send_Serial_State(controller_ID);
    if(g_pstn_callback != NULL)
    {
        if(g_dte_status & CARRIER_ACTIVATION_CHECK)
        {
            g_pstn_callback(controller_ID, USB_APP_CDC_CARRIER_ACTIVATED,
                NULL);
        }
        else
        {
            g_pstn_callback(controller_ID, USB_APP_CDC_CARRIER_DEACTIVATED,
                NULL);
        }
    }
    return USB_OK;
}

/*
** ===================================================================
**     Method      :  USB_Class_CDC_PSTN_Send_Break (component USB_CDC_CLASS)
**     Description :
**         This function is called in response to Set Config request
**     Parameters  :
**         NAME            - DESCRIPTION
**         controller_ID   - [IN] Controller ID
**       * setup_packet    - [IN] Pointer to setup
**                           packet
**       * data            - [OUT] Pointer to Data to be send
**       * size            - [OUT] Pointer to Size of Data
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint_8 USB_Class_CDC_PSTN_Send_Break(uint_8 controller_ID, USB_SETUP_STRUCT *setup_packet, uint_8_ptr *data, USB_PACKET_SIZE *size)
{

    UNUSED (controller_ID)
    UNUSED (data)
    *size = 0;

    g_break_duration = setup_packet->value;

    return USB_OK;
}

/*
** ===================================================================
**     Method      :  usb_cdc_USB_Class_CDC_PSTN_Get_Comm_Feature (component USB_CDC_CLASS)
**     Description :
**         This function is called in response to Set Config request
**     Parameters  :
**         NAME            - DESCRIPTION
**         controller_ID   - [IN] Controller ID
**       * setup_packet    - [IN] Pointer to setup
**                           packet
**       * data            - [OUT] Pointer to Data to be send
**       * size            - [OUT] Pointer to Size of Data
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint_8 USB_Class_CDC_PSTN_Get_Comm_Feature(uint_8 controller_ID, USB_SETUP_STRUCT *setup_packet, uint_8_ptr *data, USB_PACKET_SIZE *size)
{
    uint_8 status;
    status = USB_OK;
    *size = COMM_FEATURE_DATA_SIZE;
    g_current_interface = (uint_8)setup_packet->index ;
    if(setup_packet->value == ABSTRACT_STATE_FEATURE)
    {
        status = USB_Desc_Get_Abstract_State(controller_ID,
            g_current_interface, data);
    }
    else if(setup_packet->value == COUNTRY_SETTING_FEATURE)
    {
        status = USB_Desc_Get_Country_Setting(controller_ID,
            g_current_interface, data);
    }
    else
    {
        *size = 0; /* for Reserved/Invalid Feature Selector Value */
    }
    return status;
}

/*
** ===================================================================
**     Method      :  usb_cdc_USB_Class_CDC_PSTN_Set_Comm_Feature (component USB_CDC_CLASS)
**     Description :
**         This function is called in response to SetCommFeature request
**     Parameters  :
**         NAME            - DESCRIPTION
**         controller_ID   - [IN] Controller ID
**       * setup_packet    - [IN] Pointer to setup
**                           packet
**       * data            - [OUT] Pointer to Data to be send
**       * size            - [OUT] Pointer to Size of Data
**     Returns     :
**         ---             - Error code
** ===================================================================
*/
uint_8 USB_Class_CDC_PSTN_Set_Comm_Feature(uint_8 controller_ID, USB_SETUP_STRUCT *setup_packet, uint_8_ptr *data, USB_PACKET_SIZE *size)
{
    uint_8 status;
    status = USB_OK;
    *size = COMM_FEATURE_DATA_SIZE;
    g_current_interface = (uint_8)setup_packet->index ;
    if(setup_packet->value == ABSTRACT_STATE_FEATURE)
    {
        status = USB_Desc_Set_Abstract_State(controller_ID,
            g_current_interface, data);
    }
    else if(setup_packet->value == COUNTRY_SETTING_FEATURE)
    {
        status = USB_Desc_Set_Country_Setting(controller_ID,
            g_current_interface, data);
    }
    else
    {
        *size = 0; /* for Reserved/Invalid Feature Selector Value */
    }
    return status;
}
/*
** ===================================================================
**     Method      :  USB_Class_CDC_PSTN_Send_Serial_State (component USB_CDC_CLASS)
**     Description :
**         This function is called to send serial state notification
**     Parameters  :
**         NAME            - DESCRIPTION
**         controller_ID   - [IN] Controller ID
**     Returns     : Nothing
** ===================================================================
*/
void USB_Class_CDC_PSTN_Send_Serial_State(uint_8 controller_ID)
{
    /* update array for current interface */
    g_serial_state_buf[4] = g_current_interface;
    /* Lower byte of UART BITMAP */
    g_serial_state_buf[NOTIF_PACKET_SIZE+UART_BITMAP_SIZE-2] =
        g_uart_bitmap._byte;
    (void)USB_Class_CDC_Interface_CIC_Send_Data(controller_ID,
        g_serial_state_buf, (NOTIF_PACKET_SIZE + UART_BITMAP_SIZE));
}
/* END usb_cdc. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.2 [05.07]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
